version: '3'

services:
 web:
  container_name: kae-nginx-serv
  restart: always
  image: nginx:alpine
  ports:
   - 8090:80
  volumes:
   - ./public_html:/public_html
   - ./conf.d:/etc/nginx/conf.d
  networks:
   - nginxphp

 php:
  container_name: kae-php-serv
  restart: always
  image: php:8.0.0RC3-fpm-alpine
  volumes:
   - ./public_html:/public_html
  expose:
   - 9000
  networks:
   - nginxphp

networks:
 nginxphp:
